config/routes.rb
Rails.application.routes.draw do

  resources :course_categories
  resources :users, only: [:new, :create]
  

  #root 'signin#index'
  root 'landing#home'

  #The blog spot

  mount Lines::Engine => "/blog"
  
  #the landing spot
  
  get 'home', to: 'landing#home'
  get 'about_us', to: 'landing#about_us'
  get 'contact', to: 'landing#contact'
  get 'courses', to: 'landing#courses'

  #
  get '/course/:id', to: 'courses#show_course'

  #lms

  get 'lms', to: 'signin#index'

  get '/courses/:id/image', to: 'courses#show_image'
  get '/snippets/:id/image', to: 'snippets#show_image'
  get '/users/:id/image', to: 'users#show_image'
  get '/outcome_files/:id/upload', to: 'outcome_files#show_upload'
  match ':controller(/:action(/:id(.:format)))', via: %i[get post put patch]

  

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  course_id  :integer
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ApplicationRecord
  belongs_to :course, touch: true
  has_many :goals_objectives, dependent: :destroy
  has_many :lessons, through: :goals_objectives
  has_many :objectives, -> { order(id: :asc) }, through: :goals_objectives
  validates_presence_of :title
end

app/models/message_template.rb
# == Schema Information
#
# Table name: message_templates
#
#  id           :integer          not null, primary key
#  manager_id   :integer
#  content_id   :integer
#  objective_id :integer
#  counter      :integer          default(0)
#  message      :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class MessageTemplate < ApplicationRecord
  belongs_to :content
  belongs_to :manager, class_name: 'User'
  belongs_to :objective
  validates_presence_of :content_id
  validates_presence_of :manager_id
  validates_presence_of :message
  validates_presence_of :objective_id
end

app/controllers/message_templates_controller.rb
class MessageTemplatesController < ApplicationController
  # ====================================================================
  # Public Functions
  # ====================================================================
  def ajax_create
    message_template = MessageTemplate.new(message: params[:message], manager_id: session[:id], content_id: params[:content_id].to_i, objective_id: params[:objective_id].to_i)
    message_template.save
    set_message_templates
  end

  def ajax_count
    message_template = MessageTemplate.find params[:id]
    updated_counter = (message_template.counter + 1) % 100_000
    message_template.update_attributes(counter: updated_counter) if message_template && (message_template.content_id > 0)
    set_message_templates
  end

  def ajax_destroy
    message_template = MessageTemplate.find params[:id]
    message_template.destroy if message_template && (message_template.manager_id == session[:id])
    set_message_templates
  end

  def ajax_toggle_contents
    message_template = MessageTemplate.find params[:id]
    message_template.update_attributes(content_id: params[:toggled_content_id].to_i, objective_id: 0)
    set_message_templates
  end

  def ajax_toggle_objective
    message_template = MessageTemplate.find params[:id]
    objective_id = message_template.objective_id == params[:objective_id].to_i ? 0 : params[:objective_id].to_i
    message_template.update_attributes(content_id: session[:content_id], objective_id: objective_id)
    set_message_templates
  end

  # ====================================================================
  # Private Functions
  # ====================================================================

  private

  def set_message_templates
    @content = Content.find session[:content_id]
    @message_templates = get_message_templates(true)

    # outcomes are needed to refresh all outcome insert_btn in assignment_page
    lesson_id = params[:lesson_id]
    lesson = Lesson.find lesson_id
    evaluator_id = lesson.evaluator_id
    outcomes = Outcome.all_by_lesson_id_and_lesson_role_and_manager_id session[:nav_id], lesson_id, 'evaluator', session[:id]
    render 'layouts/renders/message_templates', locals: { lesson_id: lesson_id, evaluator_id: evaluator_id, outcomes: outcomes }
  end
end

app/helpers/message_templates_helper.rb
module MessageTemplatesHelper
  # ====================================================================
  # Public Functions
  # ====================================================================

  def dropdown_position(text, left_max_size)
    text.size <= left_max_size ? '' : 'pull-right'
  end

  def template_btn_class(content_id, objective_id)
    return 'btn btn-sm btn-success' if content_id.zero?
    return 'btn btn-sm btn-warning' if objective_id > 0
    'btn btn-sm btn-light'
  end
end

app/views/message_templates/_create_btn.html.erb
<!-- Example split danger button -->
<div class="btn-group dropup" style="float: left; margin-left: 10px;">
  <button type="button" id="create_template_<%= outcome_id %>" class="btn btn-light btn-lg"><i class='fa fa-comment'></i> Register in template</button>
  <button type="button" id="create_message_template_option_<%= outcome_id %>" class="btn btn-light btn-lg dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>

  <div class="dropdown-menu" aria-labelledby="create_template_<%= outcome_id %>">
    <% if evaluator_id > 0 %>
    <% @content.objectives.each_with_index do |obj, index| %>
    <a id="create_demerit_template_<%= outcome_id %>_<%= obj.id %>" class="create_template_obj_<%= obj.id %> dropdown-item" style="cursor:pointer;" disabled="disabled">Register in the deduction template of target <% = index + 1%></a>
    <% end %>
    <% end %>
    <a id="create_common_template_<%= outcome_id %>" class="dropdown-item" style="cursor:pointer;">Register to all teaching material template</a>
  </div>
</div>


<script>
$("#create_template_<%= outcome_id %>").click(function(){createTemplate(<%= lesson_id %>, <%= outcome_id %>, <%= @content.id %>, 0);})

<% if evaluator_id > 0 %>
<% @content.objectives.each_with_index do |obj, index| %>
$("#create_demerit_template_<%= outcome_id %>_<%= obj.id %>").click(function(){createTemplate(<%= lesson_id %>, <%= outcome_id %>, <%= @content.id %>, <%= obj.id %>);})
<% end %>
<% end %>
$("#create_common_template_<%= outcome_id %>").click(function(){createTemplate(<%= lesson_id %>, <%= outcome_id %>, 0, 0);})
</script>

app/views/message_templates/_insert_btn.html.erb
<% template = insert_btn %>
<div class="btn-group template_objective_<%= template.objective_id %>" style="float: left; margin: 0 4px 4px 0;">
  <% btn_class = template_btn_class template.content_id, template.objective_id %>
  <button type="button" id="insert_template<%= template.id %>_<%= outcome_id %>" class="<%= btn_class%> insert-btn" title="<%= template.message %>"><%= template.message %></button>
  <button type="button" class="<%= btn_class %> dropdown-toggle" style="font-size:small;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu <%= dropdown_position template.message, 14 %>">

    <% if evaluator_id > 0 %>
    <% @content.objectives.each_with_index do |obj, index| %>
    <% unchecked = (template.objective_id == obj.id) ? '' : 'unchecked' %>

    <%= link_to({controller: 'message_templates', action: 'ajax_toggle_objective', id: template.id, lesson_id: lesson_id, objective_id: obj.id}, {class: 'dropdown-item', remote: true}) do %>
    <i class='fa fa-check <%= unchecked %>'></i> Set as deduction template for target <% = index + 1%>
    <% end %>
    <% end %>
    <% end %>

    <% toggled_content_id = (template.content_id > 0) ? 0 : session[:content_id] %>
    <% unchecked = (template.content_id > 0) ? 'unchecked' : '' %>
    <%= link_to({controller: 'message_templates', action: 'ajax_toggle_contents', id: template.id, lesson_id: lesson_id, toggled_content_id: toggled_content_id}, {class: 'dropdown-item', remote: true}) do %>
    <i class='fa fa-check <%= unchecked %>'></i> Set as all teaching material template
    <% end %>

    <div class="dropdown-divider"></div>
    <%= render partial: 'layouts/buttons/delete', locals: {action_hash: {controller: 'message_templates', action: 'ajax_destroy', id: template.id, lesson_id: lesson_id}, id_attr: '', class_attr: 'dropdown-item'} %>
    <% if template.content_id > 0 %>
    <div style="float: right; margin-right:16px; font-size:x-small"><%= template.counter %>Times use</div>
    <% end %>

  </div>
</div>


<script>
var obj_ids = <%= @content.objective_ids %>

$(function () {
  var outcome_id = <%= outcome_id %>
  message_length = $("#outcome_" + outcome_id + " .message_form_text").val().length;
  displaycreateTemplateBtn(message_length, outcome_id)
  displayObjectiveTemplateBtnAll(outcome_id, obj_ids)
})
$("#insert_template<%= template.id %>_<%= outcome_id %>").click(function(){insertTemplate($(this), '<%= lesson_id %>', '<%= template.id %>', '<%= j(template.message) %>');})

</script>